### PR TITLE
update API params

### LINKED ISSUE #23: Xiaomi procedure failed: [getServiceToken] Missing serviceToken cookie
I followed the instructions to unlock my Xiaomi phone, but I found this procedure error in the current linux version and in the Windows version.

Screenshot from 2021-07-13 09-35-19

### PR DESCRIPTION
**Pull request by vmavromatis**
fix https://github.com/francescotescari/XiaoMiToolV2/issues/23

### CODE REVIEW

**Comment by 3nuc** [comment]
I'm wondering if this PR will ever get merged. The maintainer says in the README that "if you want to make changes just fork the repo". The people trying to resolve #23 for themselves would need to manually build vmavromatis's fork

**Comment by francescotescari** [comment]
> I'm wondering if this PR will ever get merged. ?

I'll review and merge PRs regularly but not often.
When I have time I'll have a look to quick updates like this one and eventually make a release.
Thanks for contributing 🚀

**Comment by TheOneWithTheBraid** [comment]
I'm unsure whether this is related to this MR, but using the proposed version, I'm getting

```
[10:38:56][PSTA  ][2560ddbd] Start process (215): "./res/tools/fastboot" "-s" "XXXXX" "oem" "unlock" "9292E49B716657B6D7F1C401A42CCCA2D830B088D339365F5D80297E687EDB506685359855CD54FBCEC3B1F6656CCD002303DF385470880960E24A8A120B63558443F2AC94C932DD201FE5C04DA271C3AA4C0DEE6282BB00BB96BABE5EC5FC424XXXXX [...]"
[10:38:56][PROC  ][4dde4cbd] Process (215) output: FAILED (Command length to RawCommand() is too long)
```

It looks like the constructed fastboot command exceeds 64 bytes. I anyway can confirm that the cookie extraction is properly fixed.

**Comment by nidhinprathap** [comment]
Any update on this release?

**Comment by nidhinprathap** [comment]
@francescotescari will a build be released ?

**Comment by meysampg** [comment]
I just ran from master branch and got this error:
```
[11:18:08][INFO  ][5656c93a] Unlock request (/api/v3/ahaUnlock) response: {"code":0,"encryptData":"A2C9ADB2553CF5AE309E4E4CEE52CBBD8D41C09292CA3EB25EB3B8E7F3C50C99B39C5813E9E326EFB6DF139CD55BA6737D645212D7A766C79AD09769E62A55A17F3FCA252DD0C4BA35E62A7B9D8228FF6EC2F139BFDE97CA2782469A5BA18208641E8A941D8D70BC628DF6D27F9AB329CF2BD31F61AC006717F1552A835C381D91CDAEB2691231122FCD9A5F655F1AA7179910B6741A47B1B6A958231AFAF9BAF1BB31860E94C8AFA3BD0BD1CA515A59CA8E71D83CAED99E0EC8AA41C110CF30B39329D1F8AB55EA79ABC29ED5C94312F982999013DA81353536E5ACD692076322532F008E03A6325C91630188CB4A45CB07032380EE0D06845FC5269D000BDC","description":"私钥签名成功","uid":"xxxxxxxx"}
[11:18:08][INFO  ][5656c93a] Unlock request response: {"code":0,"encryptData":"A2C9ADB2553CF5AE309E4E4CEE52CBBD8D41C09292CA3EB25EB3B8E7F3C50C99B39C5813E9E326EFB6DF139CD55BA6737D645212D7A766C79AD09769E62A55A17F3FCA252DD0C4BA35E62A7B9D8228FF6EC2F139BFDE97CA2782469A5BA18208641E8A941D8D70BC628DF6D27F9AB329CF2BD31F61AC006717F1552A835C381D91CDAEB2691231122FCD9A5F655F1AA7179910B6741A47B1B6A958231AFAF9BAF1BB31860E94C8AFA3BD0BD1CA515A59CA8E71D83CAED99E0EC8AA41C110CF30B39329D1F8AB55EA79ABC29ED5C94312F982999013DA81353536E5ACD692076322532F008E03A6325C91630188CB4A45CB07032380EE0D06845FC5269D000BDC","description":"私钥签名成功","uid":"xxxxxxx"}
[11:18:08][PSTA  ][5656c93a] Start process (331): "./res/tools/fastboot" "-s" "xxxxxxx" "oem" "unlock" "A2C9ADB2553CF5AE309E4E4CEE52CBBD8D41C09292CA3EB25EB3B8E7F3C50C99B39C5813E9E326EFB6DF139CD55BA6737D645212D7A766C79AD09769E62A55A17F3FCA252DD0C4BA35E62A7B9D8228FF6EC2F139BFDE97CA2782469A5BA18208641E8A941D8D70BC628DF6D27F9AB329CF2BD31F61AC006717F1552A835C381D91CDAEB2691231122FCD9A5F655F1AA7179910B6741A47B1B6A958231AFAF9BAF1BB31860E94C8AFA3BD0BD1CA515A59CA8E71D83CAED99E0EC8AA41C110CF30B39329D1F8AB55EA79ABC29ED5C94312F982999013DA81353536E5ACD692076322532F008E03A6325C91630188CB4A45CB07032380EE0D06845FC5269D000BDC"
[11:18:08][PROC  ][7be82501] Process (331) output:                                                    FAILED (Command length to RawCommand() is too long)
```

The error mentioned by @TheOneWithTheBraid is valid. 

**UPDATE**: I just merged master with linux branch on my local clone and no longer I see the mentioned problem.

**Comment by nidhinprathap** [comment]
@meysampg  is it working?
I can't get the application run on Mac. Is Java 11 Mandatory?

**Comment by meysampg** [comment]
@nidhinprathap Yes, it's unlocked my device. BTW I flashed LineageOS, and I'm stuck in the boot loop now :)).

**Comment by nidhinprathap** [comment]
> @nidhinprathap Yes, it's unlocked my device. BTW I flashed LineageOS, and I'm stuck in the boot loop now :)).

cant get it build in mac

**Comment by tsegazeabk** [comment]
> @nidhinprathap Yes, it's unlocked my device. BTW I flashed LineageOS, and I'm stuck in the boot loop now :)).

Hi pal I'm new to this stuff but I own a redmi 9 and I was trying to unlock my bootloader and the same massage above appears, and I think you are saying you fixed it can you help me out

**Comment by jeferson-guedes** [comment]
I have a problem, I did what I said there in PR, but when I log in to the xiaomi cloud, I get stuck on the code confirmation screen and even add my cell phone number and link it to the xiaomi cloud, I don't receive it through that link, I would have some parameter that could send different?

**Pull request merged**
